# Generated by Django 3.2.2 on 2021-06-03 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_comment_list_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='list',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('(deleted)'), related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
