# Generated by Django 3.2.2 on 2021-06-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
