# Generated by Django 3.2.2 on 2021-06-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_list_manual'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='winner',
            new_name='bidder',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='manual',
            new_name='close',
        ),
    ]
