# Generated by Django 3.2.2 on 2021-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_list_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='p_slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
