# Generated by Django 3.2.2 on 2021-06-21 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='whishlistx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wlistings', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.list')),
            ],
        ),
        migrations.CreateModel(
            name='whishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=700)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wlistings', models.ManyToManyField(blank=True, related_name='whish0', to='auctions.List')),
            ],
        ),
    ]
