# Generated by Django 3.2.2 on 2021-06-22 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_whishlist_whishlistx'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='whishlistx',
            new_name='Whistlistx',
        ),
        migrations.DeleteModel(
            name='whishlist',
        ),
    ]
