# Generated by Django 3.2.2 on 2021-06-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auto_20210622_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
