# Generated by Django 3.2.2 on 2021-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_list_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.ImageField(default='images/noimage.jpg', null=True, upload_to='images/'),
        ),
    ]
