# Generated by Django 3.2.2 on 2021-07-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_newpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follower_no',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='follow',
            name='following_no',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
