# Generated by Django 3.2.2 on 2021-07-20 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_follow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
