# Generated by Django 3.2.2 on 2021-08-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjtask', '0003_auto_20210816_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='counttask',
            field=models.IntegerField(default=0),
        ),
    ]
