# Generated by Django 3.2.2 on 2021-08-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjtask', '0004_projects_counttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.IntegerField(default=0),
        ),
    ]
