# Generated by Django 3.2.2 on 2021-08-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prjtask', '0005_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
        migrations.AddField(
            model_name='projects',
            name='complete',
            field=models.IntegerField(default=0),
        ),
    ]
